/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.20
 * Generated at: 2024-04-29 08:16:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class carritoCompras_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

    HttpSession objSesion=request.getSession(false);
    String usuario=(String)objSesion.getAttribute("usuario");
    if(usuario.equals("")){
        response.sendRedirect("index.jsp");
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n");
      out.write("\n");
      out.write("        <title> Cenadurí­a La Palmera </title>\n");
      out.write("        <link rel=\"icon\" type=\"image/png\" href=\"./images/logoPalmera.PNG\">\n");
      out.write("\n");
      out.write("\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("        <link\n");
      out.write("            href=\"https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap\"\n");
      out.write("            rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!-- FONT ICONS -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"fonts/icons-linear.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"fonts/icons-fontawesome/css/all.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"cartStyle.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("        <script src=\"js/jquery.js\"></script>\n");
      out.write("        <script src=\"js/scripts.js\"></script>\n");
      out.write("        <script src=\"contactform/contactform.js\"></script>\n");
      out.write("        <script src=\"js/menuscript.js\"></script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("\n");
      out.write("        <header>\n");
      out.write("            <div class=\"container psr\">\n");
      out.write("\n");
      out.write("                <div class=\"header_default\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <div class=\"site-branding\">\n");
      out.write("                        <a href=\"index.jsp\" class=\"logo\">\n");
      out.write("                            <img src=\"images/logoPalmera.PNG\" alt=\"\" class=\"logo-1\">\n");
      out.write("                            <img src=\"images/logoPalmera.PNG\" alt=\"\" class=\"logo-2\">\n");
      out.write("                        </a>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <div class=\"header-right\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <div class=\"site-navwrap\">\n");
      out.write("                            <div class=\"navicons\">\n");
      out.write("                                <a href=\"javascript:void;\" class=\"navshow\">\n");
      out.write("                                    <span class=\"lnr lnr-menu\"></span>\n");
      out.write("                                </a>\n");
      out.write("                                <a href=\"javascript:void;\" class=\"navhide\">\n");
      out.write("                                    <span class=\"lnr lnr-cross\"></span>\n");
      out.write("                                </a>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <div class=\"sitenav\" id=\"sitenav\">\n");
      out.write("                                <div class=\"navwrap\">\n");
      out.write("                                    <div class=\"navouter\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                                        <nav class=\"headermenu leftmenu\" id=\"headnav\" role=\"navigation\">\n");
      out.write("                                            <ul>\n");
      out.write("                                                <li><a href=\"menu.jsp\">Regresar al menú</a></li>\n");
      out.write("                                                <li><a>Hola ");
      out.print( usuario);
      out.write("</a></li>\n");
      out.write("                                            </ul>\n");
      out.write("                                        </nav>\n");
      out.write("\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <!--sitenav-->\n");
      out.write("                        </div>\n");
      out.write("                        <!--site-navwrap-->\n");
      out.write("\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("                <!--header_default-->\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </header>\n");
      out.write("        <!-- HEADER -->\n");
      out.write("\n");
      out.write("        <div class=\"container px-3 my-5 clearfix\">\n");
      out.write("            <!-- Shopping cart table -->\n");
      out.write("            <div class=\"card\">\n");
      out.write("                <div class=\"card-header\">\n");
      out.write("                    <h2>Carrito de compra</h2>\n");
      out.write("                    <br clear=\"all\" />\n");
      out.write("                </div>\n");
      out.write("                <div class=\"card-body\">\n");
      out.write("                    <div class=\"table-responsive\">\n");
      out.write("                        <table class=\"table table-bordered m-0\">\n");
      out.write("                            <thead>\n");
      out.write("                                <tr>\n");
      out.write("                                    <!-- Set columns width -->\n");
      out.write("                                    <th class=\"text-center py-3 px-4\" style=\"min-width: 400px;\">Nombre del platillo</th>\n");
      out.write("                                    <th class=\"text-right py-3 px-4\" style=\"width: 100px;\">Precio</th>\n");
      out.write("                                    <th class=\"text-center py-3 px-4\" style=\"width: 120px;\">Cantidad</th>\n");
      out.write("                                    <th class=\"text-right py-3 px-4\" style=\"width: 100px;\">Total</th>\n");
      out.write("                                    <th class=\"text-center align-middle py-3 px-0\" style=\"width: 40px;\"><a href=\"#\" class=\"shop-tooltip float-none text-light\" title=\"\" data-original-title=\"Clear cart\"><i class=\"ino ion-md-trash\"></i></a></th>\n");
      out.write("                                </tr>\n");
      out.write("                            </thead>\n");
      out.write("                            <tbody>\n");
      out.write("\n");
      out.write("                                <!-- ADAPTAR PARA QUE DESPLIEGUE LOS ARTICULOS DEL CARRITO-->\n");
      out.write("                                <tr>\n");
      out.write("                                    <td class=\"p-4\">\n");
      out.write("                                        <div class=\"media align-items-center\">\n");
      out.write("                                            <img src=\"https://bootdey.com/img/Content/avatar/avatar1.png\" class=\"d-block ui-w-40 ui-bordered mr-4\" alt=\"\">\n");
      out.write("                                            <div class=\"media-body\">\n");
      out.write("                                                <a href=\"#\" class=\"d-block text-dark\">CHIMICHANGAS</a>                                               \n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </td>\n");
      out.write("                                    <td class=\"text-right font-weight-semibold align-middle p-4\">$57.55</td>\n");
      out.write("                                    <td class=\"align-middle p-4\"><input type=\"text\" class=\"form-control text-center\" value=\"2\"></td>\n");
      out.write("                                    <td class=\"text-right font-weight-semibold align-middle p-4\">$115.1</td>\n");
      out.write("                                    <td class=\"text-center align-middle px-0\"><a href=\"#\" class=\"shop-tooltip close float-none text-danger\" title=\"\" data-original-title=\"Remove\">×</a></td>\n");
      out.write("                                </tr>\n");
      out.write("\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- / Shopping cart table -->\n");
      out.write("\n");
      out.write("                    <div class=\"d-flex flex-wrap justify-content-between align-items-center pb-4\">\n");
      out.write("                        <div class=\"mt-4\">\n");
      out.write("                            <label class=\"text-muted font-weight-normal\">Subtotal: </label><strong>$20</strong>                             \n");
      out.write("                            <div class=\"d-flex\">\n");
      out.write("                                <div class=\"text-right mt-4 mr-5\">\n");
      out.write("                                    <label class=\"text-muted font-weight-normal m-0\">IVA:  </label><strong>$20</strong>                                \n");
      out.write("                                    <div class=\"text-right mt-4\">\n");
      out.write("                                        <label class=\"text-muted font-weight-normal m-0\">Total:  </label><strong>$1164.65</strong>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <div class=\"float-right\">\n");
      out.write("                                <button type=\"button\" class=\"btn btn-lg btn-primary mt-2\" ><a href=\"modalCompra.jsp\">Comprar</a></button>\n");
      out.write("                                \n");
      out.write("                            </div>                           \n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <script>\n");
      out.write("                    // Ventana modal\n");
      out.write("                    var modal = document.getElementById(\"ventanaModal\");\n");
      out.write("                    // Botón que abre el modal\n");
      out.write("                    var boton = document.getElementById(\"abrirModal\");\n");
      out.write("                    // Hace referencia al elemento <span> que tiene la X que cierra la ventana\n");
      out.write("                    var span = document.getElementsByClassName(\"cerrar\")[0];\n");
      out.write("\n");
      out.write("                    boton.addEventListener(\"click\", function () {\n");
      out.write("                        modal.style.display = \"block\";\n");
      out.write("                    });\n");
      out.write("                    // Si el usuario hace clic en la x, la ventana se cierra\n");
      out.write("                    span.addEventListener(\"click\", function () {\n");
      out.write("                        modal.style.display = \"none\";\n");
      out.write("                    });\n");
      out.write("                    // Si el  usuario hace clic fuera de la ventana, se cierra.\n");
      out.write("                    window.addEventListener(\"click\", function (event) {\n");
      out.write("                        if (event.target == modal) {\n");
      out.write("                            modal.style.display = \"none\";\n");
      out.write("                        }\n");
      out.write("                    });\n");
      out.write("                </script>\n");
      out.write("\n");
      out.write("                <footer>\n");
      out.write("                    <div class=\"container\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <div class=\"copyright\">\n");
      out.write("                            Copyright &copy; <span id=\"copyrightyear\"></span> Equipo Aplicaciones Web\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                </footer>\n");
      out.write("                <!-- FOOTER -->\n");
      out.write("\n");
      out.write("\n");
      out.write("                </body>\n");
      out.write("                </html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
